import React from 'react'

export interface IntrinsicElements {
  // HTML
  a: React.DetailedReactHTMLElement<React.AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>;
  abbr: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  address: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  area: React.DetailedReactHTMLElement<React.AreaHTMLAttributes<HTMLAreaElement>, HTMLAreaElement>;
  article: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  aside: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  audio: React.DetailedReactHTMLElement<React.AudioHTMLAttributes<HTMLAudioElement>, HTMLAudioElement>;
  b: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  base: React.DetailedReactHTMLElement<React.BaseHTMLAttributes<HTMLBaseElement>, HTMLBaseElement>;
  bdi: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  bdo: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  big: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  blockquote: React.DetailedReactHTMLElement<React.BlockquoteHTMLAttributes<HTMLQuoteElement>, HTMLQuoteElement>;
  body: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLBodyElement>, HTMLBodyElement>;
  br: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLBRElement>, HTMLBRElement>;
  button: React.DetailedReactHTMLElement<React.ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>;
  canvas: React.DetailedReactHTMLElement<React.CanvasHTMLAttributes<HTMLCanvasElement>, HTMLCanvasElement>;
  caption: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  center: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  cite: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  code: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  col: React.DetailedReactHTMLElement<React.ColHTMLAttributes<HTMLTableColElement>, HTMLTableColElement>;
  colgroup: React.DetailedReactHTMLElement<React.ColgroupHTMLAttributes<HTMLTableColElement>, HTMLTableColElement>;
  data: React.DetailedReactHTMLElement<React.DataHTMLAttributes<HTMLDataElement>, HTMLDataElement>;
  datalist: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLDataListElement>, HTMLDataListElement>;
  dd: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  del: React.DetailedReactHTMLElement<React.DelHTMLAttributes<HTMLModElement>, HTMLModElement>;
  details: React.DetailedReactHTMLElement<React.DetailsHTMLAttributes<HTMLDetailsElement>, HTMLDetailsElement>;
  dfn: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  dialog: React.DetailedReactHTMLElement<React.DialogHTMLAttributes<HTMLDialogElement>, HTMLDialogElement>;
  div: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLDivElement>, HTMLDivElement>;
  dl: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLDListElement>, HTMLDListElement>;
  dt: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  em: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  embed: React.DetailedReactHTMLElement<React.EmbedHTMLAttributes<HTMLEmbedElement>, HTMLEmbedElement>;
  fieldset: React.DetailedReactHTMLElement<React.FieldsetHTMLAttributes<HTMLFieldSetElement>, HTMLFieldSetElement>;
  figcaption: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  figure: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  footer: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  form: React.DetailedReactHTMLElement<React.FormHTMLAttributes<HTMLFormElement>, HTMLFormElement>;
  h1: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>;
  h2: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>;
  h3: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>;
  h4: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>;
  h5: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>;
  h6: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>;
  head: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLHeadElement>, HTMLHeadElement>;
  header: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  hgroup: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  hr: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLHRElement>, HTMLHRElement>;
  html: React.DetailedReactHTMLElement<React.HtmlHTMLAttributes<HTMLHtmlElement>, HTMLHtmlElement>;
  i: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  iframe: React.DetailedReactHTMLElement<React.IframeHTMLAttributes<HTMLIFrameElement>, HTMLIFrameElement>;
  img: React.DetailedReactHTMLElement<React.ImgHTMLAttributes<HTMLImageElement>, HTMLImageElement>;
  input: React.DetailedReactHTMLElement<React.InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>;
  ins: React.DetailedReactHTMLElement<React.InsHTMLAttributes<HTMLModElement>, HTMLModElement>;
  kbd: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  keygen: React.DetailedReactHTMLElement<React.KeygenHTMLAttributes<HTMLElement>, HTMLElement>;
  label: React.DetailedReactHTMLElement<React.LabelHTMLAttributes<HTMLLabelElement>, HTMLLabelElement>;
  legend: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLLegendElement>, HTMLLegendElement>;
  li: React.DetailedReactHTMLElement<React.LiHTMLAttributes<HTMLLIElement>, HTMLLIElement>;
  link: React.DetailedReactHTMLElement<React.LinkHTMLAttributes<HTMLLinkElement>, HTMLLinkElement>;
  main: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  map: React.DetailedReactHTMLElement<React.MapHTMLAttributes<HTMLMapElement>, HTMLMapElement>;
  mark: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  menu: React.DetailedReactHTMLElement<React.MenuHTMLAttributes<HTMLElement>, HTMLElement>;
  menuitem: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  meta: React.DetailedReactHTMLElement<React.MetaHTMLAttributes<HTMLMetaElement>, HTMLMetaElement>;
  meter: React.DetailedReactHTMLElement<React.MeterHTMLAttributes<HTMLMeterElement>, HTMLMeterElement>;
  nav: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  noindex: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  noscript: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  object: React.DetailedReactHTMLElement<React.ObjectHTMLAttributes<HTMLObjectElement>, HTMLObjectElement>;
  ol: React.DetailedReactHTMLElement<React.OlHTMLAttributes<HTMLOListElement>, HTMLOListElement>;
  optgroup: React.DetailedReactHTMLElement<React.OptgroupHTMLAttributes<HTMLOptGroupElement>, HTMLOptGroupElement>;
  option: React.DetailedReactHTMLElement<React.OptionHTMLAttributes<HTMLOptionElement>, HTMLOptionElement>;
  output: React.DetailedReactHTMLElement<React.OutputHTMLAttributes<HTMLOutputElement>, HTMLOutputElement>;
  p: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLParagraphElement>, HTMLParagraphElement>;
  param: React.DetailedReactHTMLElement<React.ParamHTMLAttributes<HTMLParamElement>, HTMLParamElement>;
  picture: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  pre: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLPreElement>, HTMLPreElement>;
  progress: React.DetailedReactHTMLElement<React.ProgressHTMLAttributes<HTMLProgressElement>, HTMLProgressElement>;
  q: React.DetailedReactHTMLElement<React.QuoteHTMLAttributes<HTMLQuoteElement>, HTMLQuoteElement>;
  rp: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  rt: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  ruby: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  s: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  samp: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  search: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  slot: React.DetailedReactHTMLElement<React.SlotHTMLAttributes<HTMLSlotElement>, HTMLSlotElement>;
  script: React.DetailedReactHTMLElement<React.ScriptHTMLAttributes<HTMLScriptElement>, HTMLScriptElement>;
  section: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  select: React.DetailedReactHTMLElement<React.SelectHTMLAttributes<HTMLSelectElement>, HTMLSelectElement>;
  small: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  source: React.DetailedReactHTMLElement<React.SourceHTMLAttributes<HTMLSourceElement>, HTMLSourceElement>;
  span: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLSpanElement>, HTMLSpanElement>;
  strong: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  style: React.DetailedReactHTMLElement<React.StyleHTMLAttributes<HTMLStyleElement>, HTMLStyleElement>;
  sub: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  summary: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  sup: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  table: React.DetailedReactHTMLElement<React.TableHTMLAttributes<HTMLTableElement>, HTMLTableElement>;
  template: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLTemplateElement>, HTMLTemplateElement>;
  tbody: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLTableSectionElement>, HTMLTableSectionElement>;
  td: React.DetailedReactHTMLElement<React.TdHTMLAttributes<HTMLTableDataCellElement>, HTMLTableDataCellElement>;
  textarea: React.DetailedReactHTMLElement<React.TextareaHTMLAttributes<HTMLTextAreaElement>, HTMLTextAreaElement>;
  tfoot: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLTableSectionElement>, HTMLTableSectionElement>;
  th: React.DetailedReactHTMLElement<React.ThHTMLAttributes<HTMLTableHeaderCellElement>, HTMLTableHeaderCellElement>;
  thead: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLTableSectionElement>, HTMLTableSectionElement>;
  time: React.DetailedReactHTMLElement<React.TimeHTMLAttributes<HTMLTimeElement>, HTMLTimeElement>;
  title: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLTitleElement>, HTMLTitleElement>;
  tr: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLTableRowElement>, HTMLTableRowElement>;
  track: React.DetailedReactHTMLElement<React.TrackHTMLAttributes<HTMLTrackElement>, HTMLTrackElement>;
  u: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  ul: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLUListElement>, HTMLUListElement>;
  "var": React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  video: React.DetailedReactHTMLElement<React.VideoHTMLAttributes<HTMLVideoElement>, HTMLVideoElement>;
  wbr: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  webview: React.DetailedReactHTMLElement<React.WebViewHTMLAttributes<HTMLWebViewElement>, HTMLWebViewElement>;

  // SVG
  svg: React.ReactSVGElement<SVGSVGElement>;

  animate: React.ReactSVGElement<SVGElement>; // TODO: It is SVGAnimateElement but is not in TypeScript's lib.dom.d.ts for now.
  animateMotion: React.ReactSVGElement<SVGElement>;
  animateTransform: React.ReactSVGElement<SVGElement>; // TODO: It is SVGAnimateTransformElement but is not in TypeScript's lib.dom.d.ts for now.
  circle: React.ReactSVGElement<SVGCircleElement>;
  clipPath: React.ReactSVGElement<SVGClipPathElement>;
  defs: React.ReactSVGElement<SVGDefsElement>;
  desc: React.ReactSVGElement<SVGDescElement>;
  ellipse: React.ReactSVGElement<SVGEllipseElement>;
  feBlend: React.ReactSVGElement<SVGFEBlendElement>;
  feColorMatrix: React.ReactSVGElement<SVGFEColorMatrixElement>;
  feComponentTransfer: React.ReactSVGElement<SVGFEComponentTransferElement>;
  feComposite: React.ReactSVGElement<SVGFECompositeElement>;
  feConvolveMatrix: React.ReactSVGElement<SVGFEConvolveMatrixElement>;
  feDiffuseLighting: React.ReactSVGElement<SVGFEDiffuseLightingElement>;
  feDisplacementMap: React.ReactSVGElement<SVGFEDisplacementMapElement>;
  feDistantLight: React.ReactSVGElement<SVGFEDistantLightElement>;
  feDropShadow: React.ReactSVGElement<SVGFEDropShadowElement>;
  feFlood: React.ReactSVGElement<SVGFEFloodElement>;
  feFuncA: React.ReactSVGElement<SVGFEFuncAElement>;
  feFuncB: React.ReactSVGElement<SVGFEFuncBElement>;
  feFuncG: React.ReactSVGElement<SVGFEFuncGElement>;
  feFuncR: React.ReactSVGElement<SVGFEFuncRElement>;
  feGaussianBlur: React.ReactSVGElement<SVGFEGaussianBlurElement>;
  feImage: React.ReactSVGElement<SVGFEImageElement>;
  feMerge: React.ReactSVGElement<SVGFEMergeElement>;
  feMergeNode: React.ReactSVGElement<SVGFEMergeNodeElement>;
  feMorphology: React.ReactSVGElement<SVGFEMorphologyElement>;
  feOffset: React.ReactSVGElement<SVGFEOffsetElement>;
  fePointLight: React.ReactSVGElement<SVGFEPointLightElement>;
  feSpecularLighting: React.ReactSVGElement<SVGFESpecularLightingElement>;
  feSpotLight: React.ReactSVGElement<SVGFESpotLightElement>;
  feTile: React.ReactSVGElement<SVGFETileElement>;
  feTurbulence: React.ReactSVGElement<SVGFETurbulenceElement>;
  filter: React.ReactSVGElement<SVGFilterElement>;
  foreignObject: React.ReactSVGElement<SVGForeignObjectElement>;
  g: React.ReactSVGElement<SVGGElement>;
  image: React.ReactSVGElement<SVGImageElement>;
  line: React.ReactSVGElement<SVGLineElement>;
  linearGradient: React.ReactSVGElement<SVGLinearGradientElement>;
  marker: React.ReactSVGElement<SVGMarkerElement>;
  mask: React.ReactSVGElement<SVGMaskElement>;
  metadata: React.ReactSVGElement<SVGMetadataElement>;
  mpath: React.ReactSVGElement<SVGElement>;
  path: React.ReactSVGElement<SVGPathElement>;
  pattern: React.ReactSVGElement<SVGPatternElement>;
  polygon: React.ReactSVGElement<SVGPolygonElement>;
  polyline: React.ReactSVGElement<SVGPolylineElement>;
  radialGradient: React.ReactSVGElement<SVGRadialGradientElement>;
  rect: React.ReactSVGElement<SVGRectElement>;
  set: React.ReactSVGElement<SVGSetElement>;
  stop: React.ReactSVGElement<SVGStopElement>;
  switch: React.ReactSVGElement<SVGSwitchElement>;
  symbol: React.ReactSVGElement<SVGSymbolElement>;
  text: React.ReactSVGElement<SVGTextElement>;
  textPath: React.ReactSVGElement<SVGTextPathElement>;
  tspan: React.ReactSVGElement<SVGTSpanElement>;
  use: React.ReactSVGElement<SVGUseElement>;
  view: React.ReactSVGElement<SVGViewElement>;
}

export interface IntrinsicElementsWithAdditionalProps<A> {
  // HTML
  a: React.DetailedReactHTMLElement<React.AnchorHTMLAttributes<HTMLAnchorElement> & A, HTMLAnchorElement>;
  abbr: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  address: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  area: React.DetailedReactHTMLElement<React.AreaHTMLAttributes<HTMLAreaElement> & A, HTMLAreaElement>;
  article: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  aside: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  audio: React.DetailedReactHTMLElement<React.AudioHTMLAttributes<HTMLAudioElement> & A, HTMLAudioElement>;
  b: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  base: React.DetailedReactHTMLElement<React.BaseHTMLAttributes<HTMLBaseElement> & A, HTMLBaseElement>;
  bdi: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  bdo: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  big: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  blockquote: React.DetailedReactHTMLElement<React.BlockquoteHTMLAttributes<HTMLQuoteElement> & A, HTMLQuoteElement>;
  body: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLBodyElement> & A, HTMLBodyElement>;
  br: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLBRElement> & A, HTMLBRElement>;
  button: React.DetailedReactHTMLElement<React.ButtonHTMLAttributes<HTMLButtonElement> & A, HTMLButtonElement>;
  canvas: React.DetailedReactHTMLElement<React.CanvasHTMLAttributes<HTMLCanvasElement> & A, HTMLCanvasElement>;
  caption: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  center: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  cite: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  code: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  col: React.DetailedReactHTMLElement<React.ColHTMLAttributes<HTMLTableColElement> & A, HTMLTableColElement>;
  colgroup: React.DetailedReactHTMLElement<React.ColgroupHTMLAttributes<HTMLTableColElement> & A, HTMLTableColElement>;
  data: React.DetailedReactHTMLElement<React.DataHTMLAttributes<HTMLDataElement> & A, HTMLDataElement>;
  datalist: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLDataListElement> & A, HTMLDataListElement>;
  dd: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  del: React.DetailedReactHTMLElement<React.DelHTMLAttributes<HTMLModElement> & A, HTMLModElement>;
  details: React.DetailedReactHTMLElement<React.DetailsHTMLAttributes<HTMLDetailsElement> & A, HTMLDetailsElement>;
  dfn: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  dialog: React.DetailedReactHTMLElement<React.DialogHTMLAttributes<HTMLDialogElement> & A, HTMLDialogElement>;
  div: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLDivElement> & A, HTMLDivElement>;
  dl: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLDListElement> & A, HTMLDListElement>;
  dt: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  em: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  embed: React.DetailedReactHTMLElement<React.EmbedHTMLAttributes<HTMLEmbedElement> & A, HTMLEmbedElement>;
  fieldset: React.DetailedReactHTMLElement<React.FieldsetHTMLAttributes<HTMLFieldSetElement> & A, HTMLFieldSetElement>;
  figcaption: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  figure: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  footer: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  form: React.DetailedReactHTMLElement<React.FormHTMLAttributes<HTMLFormElement> & A, HTMLFormElement>;
  h1: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLHeadingElement> & A, HTMLHeadingElement>;
  h2: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLHeadingElement> & A, HTMLHeadingElement>;
  h3: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLHeadingElement> & A, HTMLHeadingElement>;
  h4: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLHeadingElement> & A, HTMLHeadingElement>;
  h5: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLHeadingElement> & A, HTMLHeadingElement>;
  h6: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLHeadingElement> & A, HTMLHeadingElement>;
  head: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLHeadElement> & A, HTMLHeadElement>;
  header: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  hgroup: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  hr: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLHRElement> & A, HTMLHRElement>;
  html: React.DetailedReactHTMLElement<React.HtmlHTMLAttributes<HTMLHtmlElement> & A, HTMLHtmlElement>;
  i: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  iframe: React.DetailedReactHTMLElement<React.IframeHTMLAttributes<HTMLIFrameElement> & A, HTMLIFrameElement>;
  img: React.DetailedReactHTMLElement<React.ImgHTMLAttributes<HTMLImageElement> & A, HTMLImageElement>;
  input: React.DetailedReactHTMLElement<React.InputHTMLAttributes<HTMLInputElement> & A, HTMLInputElement>;
  ins: React.DetailedReactHTMLElement<React.InsHTMLAttributes<HTMLModElement> & A, HTMLModElement>;
  kbd: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  keygen: React.DetailedReactHTMLElement<React.KeygenHTMLAttributes<HTMLElement> & A, HTMLElement>;
  label: React.DetailedReactHTMLElement<React.LabelHTMLAttributes<HTMLLabelElement> & A, HTMLLabelElement>;
  legend: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLLegendElement> & A, HTMLLegendElement>;
  li: React.DetailedReactHTMLElement<React.LiHTMLAttributes<HTMLLIElement> & A, HTMLLIElement>;
  link: React.DetailedReactHTMLElement<React.LinkHTMLAttributes<HTMLLinkElement> & A, HTMLLinkElement>;
  main: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  map: React.DetailedReactHTMLElement<React.MapHTMLAttributes<HTMLMapElement> & A, HTMLMapElement>;
  mark: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  menu: React.DetailedReactHTMLElement<React.MenuHTMLAttributes<HTMLElement> & A, HTMLElement>;
  menuitem: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  meta: React.DetailedReactHTMLElement<React.MetaHTMLAttributes<HTMLMetaElement> & A, HTMLMetaElement>;
  meter: React.DetailedReactHTMLElement<React.MeterHTMLAttributes<HTMLMeterElement> & A, HTMLMeterElement>;
  nav: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  noindex: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  noscript: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  object: React.DetailedReactHTMLElement<React.ObjectHTMLAttributes<HTMLObjectElement> & A, HTMLObjectElement>;
  ol: React.DetailedReactHTMLElement<React.OlHTMLAttributes<HTMLOListElement> & A, HTMLOListElement>;
  optgroup: React.DetailedReactHTMLElement<React.OptgroupHTMLAttributes<HTMLOptGroupElement> & A, HTMLOptGroupElement>;
  option: React.DetailedReactHTMLElement<React.OptionHTMLAttributes<HTMLOptionElement> & A, HTMLOptionElement>;
  output: React.DetailedReactHTMLElement<React.OutputHTMLAttributes<HTMLOutputElement> & A, HTMLOutputElement>;
  p: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLParagraphElement> & A, HTMLParagraphElement>;
  param: React.DetailedReactHTMLElement<React.ParamHTMLAttributes<HTMLParamElement> & A, HTMLParamElement>;
  picture: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  pre: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLPreElement> & A, HTMLPreElement>;
  progress: React.DetailedReactHTMLElement<React.ProgressHTMLAttributes<HTMLProgressElement> & A, HTMLProgressElement>;
  q: React.DetailedReactHTMLElement<React.QuoteHTMLAttributes<HTMLQuoteElement> & A, HTMLQuoteElement>;
  rp: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  rt: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  ruby: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  s: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  samp: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  search: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  slot: React.DetailedReactHTMLElement<React.SlotHTMLAttributes<HTMLSlotElement> & A, HTMLSlotElement>;
  script: React.DetailedReactHTMLElement<React.ScriptHTMLAttributes<HTMLScriptElement> & A, HTMLScriptElement>;
  section: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  select: React.DetailedReactHTMLElement<React.SelectHTMLAttributes<HTMLSelectElement> & A, HTMLSelectElement>;
  small: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  source: React.DetailedReactHTMLElement<React.SourceHTMLAttributes<HTMLSourceElement> & A, HTMLSourceElement>;
  span: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLSpanElement> & A, HTMLSpanElement>;
  strong: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  style: React.DetailedReactHTMLElement<React.StyleHTMLAttributes<HTMLStyleElement> & A, HTMLStyleElement>;
  sub: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  summary: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  sup: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  table: React.DetailedReactHTMLElement<React.TableHTMLAttributes<HTMLTableElement> & A, HTMLTableElement>;
  template: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLTemplateElement> & A, HTMLTemplateElement>;
  tbody: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLTableSectionElement> & A, HTMLTableSectionElement>;
  td: React.DetailedReactHTMLElement<React.TdHTMLAttributes<HTMLTableDataCellElement> & A, HTMLTableDataCellElement>;
  textarea: React.DetailedReactHTMLElement<React.TextareaHTMLAttributes<HTMLTextAreaElement> & A, HTMLTextAreaElement>;
  tfoot: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLTableSectionElement> & A, HTMLTableSectionElement>;
  th: React.DetailedReactHTMLElement<React.ThHTMLAttributes<HTMLTableHeaderCellElement> & A, HTMLTableHeaderCellElement>;
  thead: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLTableSectionElement> & A, HTMLTableSectionElement>;
  time: React.DetailedReactHTMLElement<React.TimeHTMLAttributes<HTMLTimeElement> & A, HTMLTimeElement>;
  title: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLTitleElement> & A, HTMLTitleElement>;
  tr: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLTableRowElement> & A, HTMLTableRowElement>;
  track: React.DetailedReactHTMLElement<React.TrackHTMLAttributes<HTMLTrackElement> & A, HTMLTrackElement>;
  u: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  ul: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLUListElement> & A, HTMLUListElement>;
  "var": React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  video: React.DetailedReactHTMLElement<React.VideoHTMLAttributes<HTMLVideoElement> & A, HTMLVideoElement>;
  wbr: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement> & A, HTMLElement>;
  webview: React.DetailedReactHTMLElement<React.WebViewHTMLAttributes<HTMLWebViewElement> & A, HTMLWebViewElement>;

  // SVG
  svg: React.ReactSVGElement<SVGSVGElement> & A;

  animate: React.ReactSVGElement<SVGElement> & A; // TODO: It is SVGAnimateElement but is not in TypeScript's lib.dom.d.ts for now.
  animateMotion: React.ReactSVGElement<SVGElement> & A;
  animateTransform: React.ReactSVGElement<SVGElement> & A; // TODO: It is SVGAnimateTransformElement but is not in TypeScript's lib.dom.d.ts for now.
  circle: React.ReactSVGElement<SVGCircleElement> & A;
  clipPath: React.ReactSVGElement<SVGClipPathElement> & A;
  defs: React.ReactSVGElement<SVGDefsElement> & A;
  desc: React.ReactSVGElement<SVGDescElement> & A;
  ellipse: React.ReactSVGElement<SVGEllipseElement> & A;
  feBlend: React.ReactSVGElement<SVGFEBlendElement> & A;
  feColorMatrix: React.ReactSVGElement<SVGFEColorMatrixElement> & A;
  feComponentTransfer: React.ReactSVGElement<SVGFEComponentTransferElement> & A;
  feComposite: React.ReactSVGElement<SVGFECompositeElement> & A;
  feConvolveMatrix: React.ReactSVGElement<SVGFEConvolveMatrixElement> & A;
  feDiffuseLighting: React.ReactSVGElement<SVGFEDiffuseLightingElement> & A;
  feDisplacementMap: React.ReactSVGElement<SVGFEDisplacementMapElement> & A;
  feDistantLight: React.ReactSVGElement<SVGFEDistantLightElement> & A;
  feDropShadow: React.ReactSVGElement<SVGFEDropShadowElement> & A;
  feFlood: React.ReactSVGElement<SVGFEFloodElement> & A;
  feFuncA: React.ReactSVGElement<SVGFEFuncAElement> & A;
  feFuncB: React.ReactSVGElement<SVGFEFuncBElement> & A;
  feFuncG: React.ReactSVGElement<SVGFEFuncGElement> & A;
  feFuncR: React.ReactSVGElement<SVGFEFuncRElement> & A;
  feGaussianBlur: React.ReactSVGElement<SVGFEGaussianBlurElement> & A;
  feImage: React.ReactSVGElement<SVGFEImageElement> & A;
  feMerge: React.ReactSVGElement<SVGFEMergeElement> & A;
  feMergeNode: React.ReactSVGElement<SVGFEMergeNodeElement> & A;
  feMorphology: React.ReactSVGElement<SVGFEMorphologyElement> & A;
  feOffset: React.ReactSVGElement<SVGFEOffsetElement> & A;
  fePointLight: React.ReactSVGElement<SVGFEPointLightElement> & A;
  feSpecularLighting: React.ReactSVGElement<SVGFESpecularLightingElement> & A;
  feSpotLight: React.ReactSVGElement<SVGFESpotLightElement> & A;
  feTile: React.ReactSVGElement<SVGFETileElement> & A;
  feTurbulence: React.ReactSVGElement<SVGFETurbulenceElement> & A;
  filter: React.ReactSVGElement<SVGFilterElement> & A;
  foreignObject: React.ReactSVGElement<SVGForeignObjectElement> & A;
  g: React.ReactSVGElement<SVGGElement> & A;
  image: React.ReactSVGElement<SVGImageElement> & A;
  line: React.ReactSVGElement<SVGLineElement> & A;
  linearGradient: React.ReactSVGElement<SVGLinearGradientElement> & A;
  marker: React.ReactSVGElement<SVGMarkerElement> & A;
  mask: React.ReactSVGElement<SVGMaskElement> & A;
  metadata: React.ReactSVGElement<SVGMetadataElement> & A;
  mpath: React.ReactSVGElement<SVGElement> & A;
  path: React.ReactSVGElement<SVGPathElement> & A;
  pattern: React.ReactSVGElement<SVGPatternElement> & A;
  polygon: React.ReactSVGElement<SVGPolygonElement> & A;
  polyline: React.ReactSVGElement<SVGPolylineElement> & A;
  radialGradient: React.ReactSVGElement<SVGRadialGradientElement> & A;
  rect: React.ReactSVGElement<SVGRectElement> & A;
  set: React.ReactSVGElement<SVGSetElement> & A;
  stop: React.ReactSVGElement<SVGStopElement> & A;
  switch: React.ReactSVGElement<SVGSwitchElement> & A;
  symbol: React.ReactSVGElement<SVGSymbolElement> & A;
  text: React.ReactSVGElement<SVGTextElement> & A;
  textPath: React.ReactSVGElement<SVGTextPathElement> & A;
  tspan: React.ReactSVGElement<SVGTSpanElement> & A;
  use: React.ReactSVGElement<SVGUseElement> & A;
  view: React.ReactSVGElement<SVGViewElement> & A;
}
