import React from 'react'

export interface IntrinsicElementsResult {
  // HTML
  a: React.DetailedReactHTMLElement<React.AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>;
  abbr: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  address: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  area: React.DetailedReactHTMLElement<React.AreaHTMLAttributes<HTMLAreaElement>, HTMLAreaElement>;
  article: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  aside: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  audio: React.DetailedReactHTMLElement<React.AudioHTMLAttributes<HTMLAudioElement>, HTMLAudioElement>;
  b: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  base: React.DetailedReactHTMLElement<React.BaseHTMLAttributes<HTMLBaseElement>, HTMLBaseElement>;
  bdi: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  bdo: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  big: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  blockquote: React.DetailedReactHTMLElement<React.BlockquoteHTMLAttributes<HTMLQuoteElement>, HTMLQuoteElement>;
  body: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLBodyElement>, HTMLBodyElement>;
  br: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLBRElement>, HTMLBRElement>;
  button: React.DetailedReactHTMLElement<React.ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>;
  canvas: React.DetailedReactHTMLElement<React.CanvasHTMLAttributes<HTMLCanvasElement>, HTMLCanvasElement>;
  caption: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  center: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  cite: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  code: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  col: React.DetailedReactHTMLElement<React.ColHTMLAttributes<HTMLTableColElement>, HTMLTableColElement>;
  colgroup: React.DetailedReactHTMLElement<React.ColgroupHTMLAttributes<HTMLTableColElement>, HTMLTableColElement>;
  data: React.DetailedReactHTMLElement<React.DataHTMLAttributes<HTMLDataElement>, HTMLDataElement>;
  datalist: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLDataListElement>, HTMLDataListElement>;
  dd: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  del: React.DetailedReactHTMLElement<React.DelHTMLAttributes<HTMLModElement>, HTMLModElement>;
  details: React.DetailedReactHTMLElement<React.DetailsHTMLAttributes<HTMLDetailsElement>, HTMLDetailsElement>;
  dfn: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  dialog: React.DetailedReactHTMLElement<React.DialogHTMLAttributes<HTMLDialogElement>, HTMLDialogElement>;
  div: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLDivElement>, HTMLDivElement>;
  dl: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLDListElement>, HTMLDListElement>;
  dt: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  em: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  embed: React.DetailedReactHTMLElement<React.EmbedHTMLAttributes<HTMLEmbedElement>, HTMLEmbedElement>;
  fieldset: React.DetailedReactHTMLElement<React.FieldsetHTMLAttributes<HTMLFieldSetElement>, HTMLFieldSetElement>;
  figcaption: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  figure: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  footer: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  form: React.DetailedReactHTMLElement<React.FormHTMLAttributes<HTMLFormElement>, HTMLFormElement>;
  h1: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>;
  h2: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>;
  h3: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>;
  h4: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>;
  h5: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>;
  h6: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>;
  head: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLHeadElement>, HTMLHeadElement>;
  header: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  hgroup: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  hr: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLHRElement>, HTMLHRElement>;
  html: React.DetailedReactHTMLElement<React.HtmlHTMLAttributes<HTMLHtmlElement>, HTMLHtmlElement>;
  i: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  iframe: React.DetailedReactHTMLElement<React.IframeHTMLAttributes<HTMLIFrameElement>, HTMLIFrameElement>;
  img: React.DetailedReactHTMLElement<React.ImgHTMLAttributes<HTMLImageElement>, HTMLImageElement>;
  input: React.DetailedReactHTMLElement<React.InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>;
  ins: React.DetailedReactHTMLElement<React.InsHTMLAttributes<HTMLModElement>, HTMLModElement>;
  kbd: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  keygen: React.DetailedReactHTMLElement<React.KeygenHTMLAttributes<HTMLElement>, HTMLElement>;
  label: React.DetailedReactHTMLElement<React.LabelHTMLAttributes<HTMLLabelElement>, HTMLLabelElement>;
  legend: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLLegendElement>, HTMLLegendElement>;
  li: React.DetailedReactHTMLElement<React.LiHTMLAttributes<HTMLLIElement>, HTMLLIElement>;
  link: React.DetailedReactHTMLElement<React.LinkHTMLAttributes<HTMLLinkElement>, HTMLLinkElement>;
  main: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  map: React.DetailedReactHTMLElement<React.MapHTMLAttributes<HTMLMapElement>, HTMLMapElement>;
  mark: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  menu: React.DetailedReactHTMLElement<React.MenuHTMLAttributes<HTMLElement>, HTMLElement>;
  menuitem: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  meta: React.DetailedReactHTMLElement<React.MetaHTMLAttributes<HTMLMetaElement>, HTMLMetaElement>;
  meter: React.DetailedReactHTMLElement<React.MeterHTMLAttributes<HTMLMeterElement>, HTMLMeterElement>;
  nav: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  noindex: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  noscript: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  object: React.DetailedReactHTMLElement<React.ObjectHTMLAttributes<HTMLObjectElement>, HTMLObjectElement>;
  ol: React.DetailedReactHTMLElement<React.OlHTMLAttributes<HTMLOListElement>, HTMLOListElement>;
  optgroup: React.DetailedReactHTMLElement<React.OptgroupHTMLAttributes<HTMLOptGroupElement>, HTMLOptGroupElement>;
  option: React.DetailedReactHTMLElement<React.OptionHTMLAttributes<HTMLOptionElement>, HTMLOptionElement>;
  output: React.DetailedReactHTMLElement<React.OutputHTMLAttributes<HTMLOutputElement>, HTMLOutputElement>;
  p: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLParagraphElement>, HTMLParagraphElement>;
  param: React.DetailedReactHTMLElement<React.ParamHTMLAttributes<HTMLParamElement>, HTMLParamElement>;
  picture: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  pre: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLPreElement>, HTMLPreElement>;
  progress: React.DetailedReactHTMLElement<React.ProgressHTMLAttributes<HTMLProgressElement>, HTMLProgressElement>;
  q: React.DetailedReactHTMLElement<React.QuoteHTMLAttributes<HTMLQuoteElement>, HTMLQuoteElement>;
  rp: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  rt: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  ruby: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  s: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  samp: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  search: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  slot: React.DetailedReactHTMLElement<React.SlotHTMLAttributes<HTMLSlotElement>, HTMLSlotElement>;
  script: React.DetailedReactHTMLElement<React.ScriptHTMLAttributes<HTMLScriptElement>, HTMLScriptElement>;
  section: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  select: React.DetailedReactHTMLElement<React.SelectHTMLAttributes<HTMLSelectElement>, HTMLSelectElement>;
  small: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  source: React.DetailedReactHTMLElement<React.SourceHTMLAttributes<HTMLSourceElement>, HTMLSourceElement>;
  span: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLSpanElement>, HTMLSpanElement>;
  strong: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  style: React.DetailedReactHTMLElement<React.StyleHTMLAttributes<HTMLStyleElement>, HTMLStyleElement>;
  sub: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  summary: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  sup: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  table: React.DetailedReactHTMLElement<React.TableHTMLAttributes<HTMLTableElement>, HTMLTableElement>;
  template: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLTemplateElement>, HTMLTemplateElement>;
  tbody: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLTableSectionElement>, HTMLTableSectionElement>;
  td: React.DetailedReactHTMLElement<React.TdHTMLAttributes<HTMLTableDataCellElement>, HTMLTableDataCellElement>;
  textarea: React.DetailedReactHTMLElement<React.TextareaHTMLAttributes<HTMLTextAreaElement>, HTMLTextAreaElement>;
  tfoot: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLTableSectionElement>, HTMLTableSectionElement>;
  th: React.DetailedReactHTMLElement<React.ThHTMLAttributes<HTMLTableHeaderCellElement>, HTMLTableHeaderCellElement>;
  thead: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLTableSectionElement>, HTMLTableSectionElement>;
  time: React.DetailedReactHTMLElement<React.TimeHTMLAttributes<HTMLTimeElement>, HTMLTimeElement>;
  title: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLTitleElement>, HTMLTitleElement>;
  tr: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLTableRowElement>, HTMLTableRowElement>;
  track: React.DetailedReactHTMLElement<React.TrackHTMLAttributes<HTMLTrackElement>, HTMLTrackElement>;
  u: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  ul: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLUListElement>, HTMLUListElement>;
  "var": React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  video: React.DetailedReactHTMLElement<React.VideoHTMLAttributes<HTMLVideoElement>, HTMLVideoElement>;
  wbr: React.DetailedReactHTMLElement<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  webview: React.DetailedReactHTMLElement<React.WebViewHTMLAttributes<HTMLWebViewElement>, HTMLWebViewElement>;

  // SVG
  svg: React.SVGProps<SVGSVGElement>;

  animate: React.SVGProps<SVGElement>; // TODO: It is SVGAnimateElement but is not in TypeScript's lib.dom.d.ts for now.
  animateMotion: React.SVGProps<SVGElement>;
  animateTransform: React.SVGProps<SVGElement>; // TODO: It is SVGAnimateTransformElement but is not in TypeScript's lib.dom.d.ts for now.
  circle: React.SVGProps<SVGCircleElement>;
  clipPath: React.SVGProps<SVGClipPathElement>;
  defs: React.SVGProps<SVGDefsElement>;
  desc: React.SVGProps<SVGDescElement>;
  ellipse: React.SVGProps<SVGEllipseElement>;
  feBlend: React.SVGProps<SVGFEBlendElement>;
  feColorMatrix: React.SVGProps<SVGFEColorMatrixElement>;
  feComponentTransfer: React.SVGProps<SVGFEComponentTransferElement>;
  feComposite: React.SVGProps<SVGFECompositeElement>;
  feConvolveMatrix: React.SVGProps<SVGFEConvolveMatrixElement>;
  feDiffuseLighting: React.SVGProps<SVGFEDiffuseLightingElement>;
  feDisplacementMap: React.SVGProps<SVGFEDisplacementMapElement>;
  feDistantLight: React.SVGProps<SVGFEDistantLightElement>;
  feDropShadow: React.SVGProps<SVGFEDropShadowElement>;
  feFlood: React.SVGProps<SVGFEFloodElement>;
  feFuncA: React.SVGProps<SVGFEFuncAElement>;
  feFuncB: React.SVGProps<SVGFEFuncBElement>;
  feFuncG: React.SVGProps<SVGFEFuncGElement>;
  feFuncR: React.SVGProps<SVGFEFuncRElement>;
  feGaussianBlur: React.SVGProps<SVGFEGaussianBlurElement>;
  feImage: React.SVGProps<SVGFEImageElement>;
  feMerge: React.SVGProps<SVGFEMergeElement>;
  feMergeNode: React.SVGProps<SVGFEMergeNodeElement>;
  feMorphology: React.SVGProps<SVGFEMorphologyElement>;
  feOffset: React.SVGProps<SVGFEOffsetElement>;
  fePointLight: React.SVGProps<SVGFEPointLightElement>;
  feSpecularLighting: React.SVGProps<SVGFESpecularLightingElement>;
  feSpotLight: React.SVGProps<SVGFESpotLightElement>;
  feTile: React.SVGProps<SVGFETileElement>;
  feTurbulence: React.SVGProps<SVGFETurbulenceElement>;
  filter: React.SVGProps<SVGFilterElement>;
  foreignObject: React.SVGProps<SVGForeignObjectElement>;
  g: React.SVGProps<SVGGElement>;
  image: React.SVGProps<SVGImageElement>;
  line: React.SVGLineElementAttributes<SVGLineElement>;
  linearGradient: React.SVGProps<SVGLinearGradientElement>;
  marker: React.SVGProps<SVGMarkerElement>;
  mask: React.SVGProps<SVGMaskElement>;
  metadata: React.SVGProps<SVGMetadataElement>;
  mpath: React.SVGProps<SVGElement>;
  path: React.SVGProps<SVGPathElement>;
  pattern: React.SVGProps<SVGPatternElement>;
  polygon: React.SVGProps<SVGPolygonElement>;
  polyline: React.SVGProps<SVGPolylineElement>;
  radialGradient: React.SVGProps<SVGRadialGradientElement>;
  rect: React.SVGProps<SVGRectElement>;
  set: React.SVGProps<SVGSetElement>;
  stop: React.SVGProps<SVGStopElement>;
  switch: React.SVGProps<SVGSwitchElement>;
  symbol: React.SVGProps<SVGSymbolElement>;
  text: React.SVGTextElementAttributes<SVGTextElement>;
  textPath: React.SVGProps<SVGTextPathElement>;
  tspan: React.SVGProps<SVGTSpanElement>;
  use: React.SVGProps<SVGUseElement>;
  view: React.SVGProps<SVGViewElement>;
}
